server:
  port: 80

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: su
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
logging:
  level:
    root: debug
mybatis:
  config-location: classpath:mybatis-config.xml

